# Generated by Django 5.2.4 on 2025-07-15 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('size', models.BigIntegerField()),
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='FileName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='myapp.file')),
            ],
            options={
                'unique_together': {('file', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='FileAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.file')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.peer')),
            ],
            options={
                'verbose_name_plural': 'File Availabilities',
                'unique_together': {('file', 'peer')},
            },
        ),
    ]
