# Generated by Django 5.2.4 on 2025-07-14 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='fileavailability',
            options={'verbose_name_plural': 'File Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='peer',
            options={'ordering': ['-last_active']},
        ),
    ]
